### ISSUE TITLE
More documentation for NATS

### ISSUE THREAD

**Issue by wrenix** [stalwartlabs/website#55]
You are writing about components like JetStream but say also that is it more lightwight without.
So my question to the docu is, what kind of nats setup is needed to run it with stalwart.
Are there topics (or JetStream KVStore or what ever) which should we reserve for stalwart?

PS: Is the documentation correct? or should it be with `nats://`?
```toml
[store."nats"]
address = ["nats1:4222", "nats2:4222"]
```
PSS: Is it possible that handling like IMAP and/or Sieve could stop working correct, if we run a nats without JetStream?
